### Tworzenie zbioru z kodem pocztowym oraz odpowiadającym im dzielnicom
Komórki zostały powtórzone jedna po drugiej z tą różnicą że pierwsza z nich pobiera wartości które znajdują sie w tabeli na pozycjach 0 i 1 (lewa strona tabeli) następne na pozycjach 3 i 4 (prawa strona tabeli). Na koniec zbiory zsumowano.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Adres URL strony, z której chcesz pobrać tabelę
url = 'https://www.nycbynatives.com/nyc_info/new_york_city_zip_codes.php'

# Wyślij zapytanie GET do strony internetowej
response = requests.get(url)

# Sprawdź, czy żądanie się powiodło (status 200 oznacza sukces)
if response.status_code == 200:
    # Utwórz obiekt BeautifulSoup, aby przetworzyć zawartość strony
    soup = BeautifulSoup(response.text, 'html.parser')

    # Znajdź tabelę na stronie internetowej
    table = soup.find('table')

    # Jeśli znaleziono tabelę
    if table:
        # Inicjuj puste listy dla danych
        districts = []
        zip_codes = []

        # Iteruj przez wiersze tabeli
        for row in table.find_all('tr')[0:]:
            cells = row.find_all('td')
            district = cells[0].text.strip()
            zip_code = cells[1].text.strip().split(', ')
            for code in zip_code:
                districts.append(district)
                zip_codes.append(code)

        # Tworzymy DataFrame z zebranych danych
        df_a = pd.DataFrame({'ZIP CODE': districts, 'BOROUGH': zip_codes})

        # Wyświetlamy lub zapisujemy DataFrame
        print(df_a)
        # df.to_csv('zipcode_district_data.csv', index=False)
    else:
        print('Nie znaleziono żadnej tabeli na stronie.')
else:
    print('Nie udało się pobrać zawartości strony.')

    ZIP CODE    BOROUGH
0      10001  Manhattan
1      10002  Manhattan
2      10003  Manhattan
3      10004  Manhattan
4      10005  Manhattan
..       ...        ...
235    11691     Queens
236    11692     Queens
237    11693     Queens
238    11694     Queens
239    11697     Queens

[240 rows x 2 columns]

In [2]:
# Adres URL strony, z której chcesz pobrać tabelę
url = 'https://www.nycbynatives.com/nyc_info/new_york_city_zip_codes.php'

# Wyślij zapytanie GET do strony internetowej
response = requests.get(url)

# Sprawdź, czy żądanie się powiodło (status 200 oznacza sukces)
if response.status_code == 200:
    # Utwórz obiekt BeautifulSoup, aby przetworzyć zawartość strony
    soup = BeautifulSoup(response.text, 'html.parser')

    # Znajdź tabelę na stronie internetowej
    table = soup.find('table')

    # Jeśli znaleziono tabelę
    if table:
        # Inicjuj puste listy dla danych
        districts = []
        zip_codes = []

        # Iteruj przez wiersze tabeli
        for row in table.find_all('tr')[0:]:
            cells = row.find_all('td')
            district = cells[3].text.strip()
            zip_code = cells[4].text.strip().split(', ')
            for code in zip_code:
                districts.append(district)
                zip_codes.append(code)

        # Tworzymy DataFrame z zebranych danych
        df_b = pd.DataFrame({'ZIP CODE': districts, 'BOROUGH': zip_codes})

        # Wyświetlamy DataFrame
        print(df_b)
    else:
        print('Nie znaleziono żadnej tabeli na stronie.')
else:
    print('Nie udało się pobrać zawartości strony.')

    ZIP CODE BOROUGH
0      10451   Bronx
1      10452   Bronx
2      10453   Bronx
3      10454   Bronx
4      10455   Bronx
..       ...     ...
235    10309  Staten
236    10310  Staten
237    10311  Staten
238    10312  Staten
239    10314  Staten

[240 rows x 2 columns]

In [3]:
df = pd.concat([df_a, df_b], ignore_index=True)
df['BOROUGH'] = df['BOROUGH'].replace('Staten', 'Staten Island')
df = df.sort_values(by='ZIP CODE')
df.reset_index(drop = True)

    ZIP CODE    BOROUGH
0      10001  Manhattan
1      10001  Manhattan
2      10002  Manhattan
3      10002  Manhattan
4      10003  Manhattan
..       ...        ...
475    11693     Queens
476    11694     Queens
477    11694     Queens
478    11697     Queens
479    11697     Queens

[480 rows x 2 columns]

In [4]:
df.to_csv('borough.csv', index=False)